ALTER TABLE IF EXISTS patients ADD COLUMN IF NOT EXISTS endereco TEXT;
ALTER TABLE IF EXISTS patients ADD COLUMN IF NOT EXISTS ativo BOOLEAN;
UPDATE patients SET ativo = TRUE WHERE ativo IS NULL;
ALTER TABLE IF EXISTS patients ALTER COLUMN ativo SET DEFAULT TRUE;
ALTER TABLE IF EXISTS patients ALTER COLUMN ativo SET NOT NULL;

ALTER TABLE IF EXISTS patients DROP COLUMN IF EXISTS alergias;
ALTER TABLE IF EXISTS patients DROP COLUMN IF EXISTS historico_vacinas;
ALTER TABLE IF EXISTS allergies ADD COLUMN IF NOT EXISTS severidade VARCHAR(20);
ALTER TABLE IF EXISTS vaccines ADD COLUMN IF NOT EXISTS lote VARCHAR(50);
ALTER TABLE IF EXISTS vaccines ADD COLUMN IF NOT EXISTS profissional_resp VARCHAR(200);
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    resource VARCHAR(100) NOT NULL,
    resource_id VARCHAR(100),
    timestamp_utc TIMESTAMP NOT NULL,
    ip_address VARCHAR(100)
);
