ALTER TABLE IF EXISTS patients ADD COLUMN IF NOT EXISTS endereco TEXT;
ALTER TABLE IF EXISTS patients ADD COLUMN IF NOT EXISTS ativo BOOLEAN;
UPDATE patients SET ativo = TRUE WHERE ativo IS NULL;
ALTER TABLE IF EXISTS patients ALTER COLUMN ativo SET DEFAULT TRUE;
ALTER TABLE IF EXISTS patients ALTER COLUMN ativo SET NOT NULL;

ALTER TABLE IF EXISTS patients DROP COLUMN IF EXISTS alergias;
ALTER TABLE IF EXISTS patients DROP COLUMN IF EXISTS historico_vacinas;